apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: cheerstag-api-dev
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/Axiom-o-Choice/cheerstag-gitops.git
        targetRevision: main
        path: apps/cheerstag-api/base
    destination:
        server: https://kubernetes.default.svc
        namespace: cheerstag-app
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
