apiVersion: apps/v1
kind: Deployment
metadata:
    name: slot-app
    namespace: slot-app
    labels:
        app: slot-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: slot-app
    template:
        metadata:
            labels:
                app: slot-app
        spec:
            containers:
                - name: web
                  image: ghcr.io/$OWNER/$APP_REPO:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  readinessProbe:
                      httpGet: { path: "/", port: 80 }
                      initialDelaySeconds: 3
                      periodSeconds: 10
                  livenessProbe:
                      httpGet: { path: "/", port: 80 }
                      initialDelaySeconds: 10
                      periodSeconds: 20
