apiVersion: apps/v1
kind: Deployment
metadata:
    name: cheerstag-app
    namespace: cheerstag-app
    labels:
        app: cheerstag-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cheerstag-app
    template:
        metadata:
            labels:
                app: cheerstag-app
        spec:
            containers:
                - name: web
                  image: ghcr.io/axiom-o-choice/cheerstag-app:b4e0a10ababbd0a0711b3d8555d45b2fb1fd7dff
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  readinessProbe:
                      httpGet: { path: "/", port: 80 }
                      initialDelaySeconds: 3
                      periodSeconds: 10
                  livenessProbe:
                      httpGet: { path: "/", port: 80 }
                      initialDelaySeconds: 10
                      periodSeconds: 20
