apiVersion: v1
kind: Service
metadata:
    name: cheerstag-app
    namespace: cheerstag-app
spec:
    selector:
        app: cheerstag-app
    ports:
        - name: http
          port: 80
          targetPort: 80
    type: ClusterIP
