apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: ingress-nginx
    namespace: argocd
    annotations:
        # make infra install before apps, optional:
        argocd.argoproj.io/sync-wave: "-10"
spec:
    project: default
    source:
        repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.11.2 # pick a fixed version
        helm:
            releaseName: ingress-nginx
            values: |
                controller:
                  ingressClassResource:
                    name: nginx
                    default: true
                  ingressClass: nginx
                  service:
                    type: LoadBalancer     # gives you a public IP (if your provider supports it)
    destination:
        server: https://kubernetes.default.svc
        namespace: ingress-nginx
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
