apiVersion: apps/v1
kind: Deployment
metadata:
    name: cheerstag-api
    namespace: cheerstag-app
    labels:
        app: cheerstag-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cheerstag-api
    template:
        metadata:
            labels:
                app: cheerstag-api
        spec:
            containers:
                - name: api
                  image: ghcr.io/axiom-o-choice/cheerstag-api:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                  readinessProbe:
                      httpGet: { path: "/", port: 3000 }
                      initialDelaySeconds: 3
                      periodSeconds: 10
                  livenessProbe:
                      httpGet: { path: "/", port: 3000 }
                      initialDelaySeconds: 10
                      periodSeconds: 20
