apiVersion: apps/v1
kind: Deployment
metadata:
    name: cheerstag-api
    namespace: cheerstag-app
    labels:
        app: cheerstag-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cheerstag-api
    template:
        metadata:
            labels:
                app: cheerstag-api
        spec:
            containers:
                - name: api
                  image: ghcr.io/axiom-o-choice/cheerstag-api:db73a4afde9711a185e08023bc0f897df3739dd7
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                  readinessProbe:
                      httpGet: { path: "/", port: 3000 }
                      initialDelaySeconds: 3
                      periodSeconds: 10
                  livenessProbe:
                      httpGet: { path: "/", port: 3000 }
                      initialDelaySeconds: 10
                      periodSeconds: 20
                  env:
                      - name: MONGODB_URI
                        valueFrom:
                            secretKeyRef:
                                name: mongo-conn # <- SealedSecret.name
                                key: MONGODB_URI # <- key inside the Secret
