---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: mongo-conn
    namespace: cheerstag-app
spec:
    encryptedData:
        MONGODB_URI: AgCPSd4E8IS7l0fvg8XNxGoDHDAa3uMnWLGrVkIiPu00KmYsBXL4C40oq6h7/fDpzAzRfwT2EyT8s83E+O5FAT+1+CZ5Hp5zHROz410XeU2aamyWW8DQB7sAYG6hvDeTehaUDaNArw4shh0LlkY7uC1JVDxkiqXRTMDWq1OSsgWS3NfPyAX/6RZdri3QclEQgJXKXRqQoZbvLY7VZhF5uOHLYQNdrCyW1ultJEFCiyD/FZZIYsi/v01sqkt8Iv8MLAqo2ZymGUo7qhSEw9c/kGXAvVCLTex2jo9XlCOWxE9dNAygeApQOEzLyts6fca9wj6iFRpHETyXFdJgp5ZiJWakHTMlIDcVp8pNlqBvTVpBJD6SmmUaxDkWuevM0SCyq4Jtt/aENZA9cvf5wFnK4TIHE7Aza/PTattcAmp9OFfaPhQQIdRgbYFH2Y0JY8RVGzjDGFaAk0dhNEZd48maBGci+UoMeD4q1XvEAOLpniU9RMf/nTgeCBV3ns4QVQONv3kzjejT+EauqHIW5biZRCpPLHQMmBA6Za4jkTVyT90I5/vCtkFvuka7a5ZWVE/QoLmkWcjSW754daQR0VUABy81Y4ayJg5DJyBIN7Dm9LWPcnph+SfMkE/kseAzck3PQhfzaDJXAQhqrvsQCLOC9zu5VbO8xHf8VHrhT8r6tgCPT4SZ0VfDzgyOsTKKd0+n09l91nTFHiHHxv/b0Ue5p6qMQdWCZ3v8O491mkKdx7TICEjXtIVVGEX74dhOO9NFrenwTW+N26xwKNqTSYn2fVppabriCI8SyIO2tmbgEBq9dcrlRhiAoA7fAU6Sl5pzJj+0B3TSc40DPrt2OFUpFW1Vfv/Io7rMZ6Q0vI4L
    template:
        metadata:
            creationTimestamp: null
            name: mongo-conn
            namespace: cheerstag-app
        type: Opaque
