apiVersion: v1
kind: Service
metadata:
    name: cheerstag-api
    namespace: cheerstag-app
spec:
    selector:
        app: cheerstag-api
    ports:
        - name: http
          port: 80
          targetPort: 3000
    type: ClusterIP
